### ISSUE TITLE
fix/ui개선(프로필 사진 관련)

### ISSUE THREAD

**Issue by 404yonara** [HabitPay/frontend#133]
1. 챌린지 메인 페이지에 시각 추가하기
2. 프사, 게시물사진 10메가 까지 올릴수있도록하기
3. 프사 비율 고치기
4. ![image](https://github.com/user-attachments/assets/7fbf6481-d68b-458f-bee5-eb2009822b78)미니 프로필 사진 z-index고치기
5. 프로필 사진 클릭시 크게 보기

**Comment by Han-Joon-Hyeok** [comment]
기능 최대한 쪼개서 이슈 생성해주시면 감사하겠습니다!
하나의 이슈 안에 비슷한 기능끼리 최대 2~3개 정도만 해주시면 리뷰할 때 조금 더 편할 것 같습니다!

**Comment by 404yonara** [comment]
넵 그렇게 해보겠습니다
